[package]
name = "endian-writer"
version = "2.3.0"
edition = "2021"
description = "[no_std] Methods for efficient reading and writing of structures to raw pointers in a stream-like fashion."
repository = "https://github.com/Sewer56/endian-writer-rs"
license-file = "../../LICENSE"
include = ["src/**/*", "README.MD"]
readme = "README.MD"

[features]
default = []

[dependencies]
concat-idents = "1.1.5"
paste = "1.0.15"

[dev-dependencies]
