name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: motivations
    attributes:
      label: Motivations
      description: If your feature request is related to a problem, please describe it.
    validations:
      required: true

  - type: dropdown
    id: work-on-implementation
    attributes:
      label: Would you like to implement this feature?
      description: Let us know if you're interested in contributing this feature
      options:
        - "Yes"
        - "No"
      default: 1
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
